apiVersion: v1
kind: Service
metadata:
  name: messagequeue
  labels:
    app: messagequeue
spec:
  selector:
    app: messagequeue
  ports:
    - name: broker
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
